"""Create initial schema.

Revision ID: ba0b60dc62a4
Revises:
Create Date: 2026-07-13 19:45:57.488239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector


revision: str = "ba0b60dc62a4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", Vector(384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(trim(answer)) > 0", name="ck_answers_answer_not_blank"
        ),
        sa.CheckConstraint(
            "char_length(trim(question)) > 0",
            name="ck_answers_question_not_blank",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_answers_content_hash"),
    )
    op.create_index(
        "ix_answers_embedding_hnsw",
        "answers",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "STARTED",
                "RETRY",
                "SUCCESS",
                "FAILURE",
                name="source_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "total_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "deleted_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(trim(filename)) > 0",
            name="ck_sources_filename_not_blank",
        ),
        sa.CheckConstraint(
            "created_count >= 0", name="ck_sources_created_count_not_negative"
        ),
        sa.CheckConstraint(
            "deleted_count >= 0", name="ck_sources_deleted_count_not_negative"
        ),
        sa.CheckConstraint(
            "total_count >= 0", name="ck_sources_total_count_not_negative"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "statistics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(trim(query)) > 0",
            name="ck_statistics_query_not_blank",
        ),
        sa.CheckConstraint(
            "execution_time_ms >= 0",
            name="ck_statistics_execution_time_not_negative",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_statistics_created_at", "statistics", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_statistics_created_at", table_name="statistics")
    op.drop_table("statistics")
    op.drop_table("sources")
    op.drop_index(
        "ix_answers_embedding_hnsw",
        table_name="answers",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("answers")
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS source_status")
    op.execute("DROP EXTENSION IF EXISTS vector")
